### ISSUE TITLE
Refactoring roadmap

### ISSUE THREAD

**Issue by wabain** [DDMAL/diva.js#321]
I'm hoping to get this done this week:

- [ ] Get more tests for events firing across the viewer lifecycle. (Look at the old callback tests, but these might need to be integrated into the navigation tests instead of standing alone.)
- [ ] Get the rest of the state changes which clear the viewer to run through `reloadViewer`.
  * [ ] Move the zoom events from `loadDocument` up
  * [ ] Get `handleZoom` to call `reloadViewer` instead of `loadDocument`
- [ ] Get internal positioning calculations to work off `viewport.top/left` instead of `horizontalOffset`, `verticalOffset` and `currentPageIndex`/`goDirectlyTo`. I think this will make a layer of complexity just go away, since viewport position changes won't have to take page positions into account. After, `currentPageIndex` will just be something to compute after location changes and `verticalOffset` and `horizontalOffset` will only be relevant for permalinking.
- [ ] Move the view-specific layout code into separate objects. Delegate to those instead of writing `if (inGrid) { ... } else { ... }`.
- [ ] Sequester the code that specifies the positions of the pages in Document and Book View and try to get page rendering and viewport changes to work without caring about what the current view or primary axis is. One thing this requires is changing how page padding is accounted for; it shouldn't be necessary to think about it after the document layout is first computed. Then hopefully it will be sufficient performance-wise to brute-force iterate through pages and then tiles to decide which ones intersect the viewport, or to take advantage of precomputed information about pages' positions relative to each other.
- [ ] Get floating-point zoom levels working. Request the images at the next-highest integer zoom level and scale them down.

**Comment by wabain** [comment]
Broken things:

- [ ] Plugins which relied at all on the elements inside the viewport (i.e., most of them...) need to be updated.
- [ ] Image requests need to be debounced.

Follow up:

- [ ] Internal positioning calculations need to be page-relative to handle scaling across zoom levels. However, currently they're all done based on the public-facing coordinate system, which is page top to viewport centre. This is hard to reason about, so the internal stuff should use the distance from page top left to viewport top left.

  * [ ] As a workaround for the difficulty of the coordinate system, various internal methods use varying coordinate information. This could/should be made more consistent.

- [ ] The Renderer class inherited a bunch of methods for getting dimension and coordinate information by default as the lowest-level class to need that information. Those should be moved somewhere else. Maybe they should live in the object returned by getDocumentLayout.

- [ ] The Diva class and the document and grid view handlers are mutating viewerState directly in a few cases. They should either go through methods of ViewerCore or just hold the state itself. The ViewerCore `getInternalState` method should be removed.

- [ ] TODO: Describe zoom issues

**Comment by wabain** [comment]
At this point I think I've covered about all the critical issues and I've gone about as far as I can commit to going. I'll be available through email or Gitter, although only sporadically for the next two weeks. It's been fun!

**Comment by jeromepl** [comment]
Can someone explain to me why image requests need to be debounced? Considering Diva often needs to load multiple tiles at a time, why would we debounce the requests?

**Comment by ahankinson** [comment]
If you scroll really quickly you don't want to load all of the images in the pages that you've skipped over.

**Comment by jeromepl** [comment]
Ahhh that makes sense. I found a TODO in the code where the debounce should occur, which is at the 'page' level if I can say. I can debounce the batch of requests for tiles on a page.

**Comment by jeromepl** [comment]
How should I go about adding a 'debounce' function? Should I copy-paste code from, say underscore.js or add a dependency/jquery plugin?

**Comment by ahankinson** [comment]
No, please don't. I would like to factor out as much jQuery as possible, so no extensions or dependencies unless it's absolutely necessary.

**Comment by jeromepl** [comment]
In the end, I had to write my own debounce function anyway, since I wasn't getting the correct behaviour with the standard one. What happened is that only the last visible page would get loaded if multiple pages would be shown within the wait timer of the debounce function.
For example, in book view, since at least two pages are always shown and loaded at once, only the right-most one would load.

My solution was to implement a debounce function that would hold the last 'n' function calls, instead of just 1 like the regular debounce does. That way, when calling the method I can pass in the number of visible pages at that time, which means only visible pages keep loading while the ones that were scrolled by too fast are cancelled as a regular debounce does.
